name: Deploy TresJS Docs

# 仅当 main 分支有 push 时触发
on:
  push:
    branches: [ main ]

permissions:
  contents: read   # 读取仓库内容
  pages: write     # 写入 Pages 分支
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3                    # 检出到 $GITHUB_WORKSPACE :contentReference[oaicite:3]{index=3}

      # 2. 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4                    # 安装 pnpm 管理器 :contentReference[oaicite:4]{index=4}

      # 3. 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 4. 打包核心库
      - name: Build core library
        run: pnpm run build                           # 生成 dist/tres.js

      # 5. 构建文档
      - name: Build docs
        run: pnpm run docs:build                      # 输出到 docs/.vitepress/dist

      # 6. 发布到 gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4           # 部署静态文件到 gh-pages :contentReference[oaicite:5]{index=5}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # 自动获取权限，无需额外配置
          publish_dir: ./docs/.vitepress/dist        # 指定构建输出目录
