permissions:
  contents: read    # 不写入源码
  pages: write      # 写入 Pages 分支
  id-token: write   # 用于 OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm install && pnpm run build && pnpm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/.vitepress/dist'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
