name: Deploy TresJS Docs

on:
  push:
    branches: [ main ]        # 仅在推 main 时触发 :contentReference[oaicite:4]{index=4}

permissions:
  contents: read             # 读取仓库内容 :contentReference[oaicite:5]{index=5}
  pages: write               # 写入 Pages 分支 :contentReference[oaicite:6]{index=6}
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    # 克隆你的代码 :contentReference[oaicite:7]{index=7}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4   # 安装 pnpm :contentReference[oaicite:8]{index=8}

      - name: Install dependencies
        run: pnpm install            # 安装所有依赖 

      - name: Build docs
        run: pnpm run docs:build     # 构建文档，输出到 docs/.vitepress/dist :contentReference[oaicite:10]{index=10}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist  # 发布目录 :contentReference[oaicite:11]{index=11}
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
